name: vuepress-deploy

on:
  push:
    branches: # listen on which branch(s)
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if git submodules were used, uncomment next line
          # submodules: true

      - uses: actions/cache@v3
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build Webpack
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        # suit with package.json
        run: yarn run build

      - name: Deploy Webpack
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # the branch to deploy on
          branch: gh-pages
          folder: .vuepress/dist

